title: Roque Quintanilla Nolazco
logo: https://github.com/Rexmaxor79/Portafolio/blob/main/INT-821136%20AGT_1093.jpg
description: BSc in Business Informatics with experience and passion in business intelligence. As a professional I seek to
understand and analyze problems to turn them into an opportunity to generate added value for my clients
offering them a solution that meets their needs.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
